# Generated by Django 4.2.30 on 2026-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                    ("archived", "Archived"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
